
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 03 14:29:00 CET 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CASO = 2;
  public static final int TIPO = 15;
  public static final int ENTERO = 5;
  public static final int SI = 13;
  public static final int ALTERNATIVAS = 8;
  public static final int AUTOINCREMENTO = 33;
  public static final int CORCHETE_CERRAR = 20;
  public static final int DOS_PUNTOS = 26;
  public static final int INT = 37;
  public static final int PARENTESIS_ABRIR = 17;
  public static final int PRINCIPAL = 11;
  public static final int CONSTANTE = 3;
  public static final int IGUAL = 30;
  public static final int SINO = 14;
  public static final int DEVUELVE = 12;
  public static final int ESCRIBE_ENT = 7;
  public static final int MIENTRAS = 9;
  public static final int ASIGNACION_SUMA = 35;
  public static final int SUMA = 27;
  public static final int ID = 36;
  public static final int PUNTO_COMA = 25;
  public static final int CORTE = 4;
  public static final int EOF = 0;
  public static final int PRODUCTO = 28;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int NEGACION = 32;
  public static final int MENOR = 29;
  public static final int ESCRIBE = 6;
  public static final int PORDEFECTO = 10;
  public static final int ASIGNACION = 34;
  public static final int LLAVE_CERRAR = 22;
  public static final int LLAVE_ABRIR = 21;
  public static final int VACIO = 16;
  public static final int CONJUNCION = 31;
  public static final int STRING = 38;
  public static final int CORCHETE_ABRIR = 19;
  public static final int PARENTESIS_CERRAR = 18;
  public static final int ALMOHADILLA = 23;
}

