
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 31 00:38:23 CEST 2021
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIPOS = 41;
  public static final int CASO = 2;
  public static final int Y = 32;
  public static final int DE = 34;
  public static final int PARENTESIS_IZQ = 14;
  public static final int DEVOLVER = 45;
  public static final int SUBPROGRAMAS = 40;
  public static final int PROGRAMA = 39;
  public static final int ENTERO = 47;
  public static final int SI = 29;
  public static final int FUNCION = 37;
  public static final int CIERTO = 25;
  public static final int RESTA = 10;
  public static final int DOS_PUNTOS = 21;
  public static final int CORCHETE_DER = 17;
  public static final int ENTONCES = 33;
  public static final int INT = 48;
  public static final int RANGO = 22;
  public static final int FIN = 28;
  public static final int PRINCIPAL = 4;
  public static final int COMIENZO = 27;
  public static final int SINO = 31;
  public static final int DEVUELVE = 5;
  public static final int CONSTANTES = 43;
  public static final int ESCRIBIR = 44;
  public static final int PROCEDIMIENTO = 38;
  public static final int SUMA = 9;
  public static final int ID = 51;
  public static final int PUNTO_COMA = 20;
  public static final int EOF = 0;
  public static final int PRODUCTO = 11;
  public static final int PARENTESIS_DER = 15;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int VECTOR = 46;
  public static final int ASIGNACION = 23;
  public static final int EN = 36;
  public static final int LLAVE_CERRAR = 7;
  public static final int NO = 30;
  public static final int VARIABLES = 42;
  public static final int LLAVE_ABRIR = 6;
  public static final int PUNTO = 19;
  public static final int VACIO = 3;
  public static final int IGUAL_QUE = 13;
  public static final int CORCHETE_IZQ = 16;
  public static final int INICIO_COMENTARIO = 8;
  public static final int FALSO = 26;
  public static final int BOOLEANO = 24;
  public static final int STRING = 49;
  public static final int PARA = 35;
  public static final int MENOR_QUE = 12;
  public static final int VAR = 50;
}

